DROP TABLE IF EXISTS exports CASCADE;
DROP TABLE IF EXISTS idea_validation CASCADE;
DROP TABLE IF EXISTS validation_dimensions CASCADE;

ALTER TABLE ideas DROP COLUMN IF EXISTS vectors;
ALTER TABLE ideas DROP COLUMN IF EXISTS signals;
ALTER TABLE ideas DROP COLUMN IF EXISTS score;
ALTER TABLE ideas DROP COLUMN IF EXISTS tags;
ALTER TABLE ideas DROP COLUMN IF EXISTS title_hash;
ALTER TABLE ideas DROP COLUMN IF EXISTS owner_id;

DROP TABLE IF EXISTS enrich_jobs CASCADE;
DROP TABLE IF EXISTS raw_items CASCADE;
DROP TABLE IF EXISTS sources CASCADE;

DROP EXTENSION IF EXISTS vector;
